import type { Metadata } from "next";
import "./globals.css";
import { AlertProvider } from "@/components/AlertProvider/AlertContext";
import { getCurrentUser } from "@/lib/curentUser";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  
  if(user === null){
    // window.location.href = '/auth'
  }

  return (
    
    <html lang="en">
      <body
        className={``}
      >
        <UserProvider user={user}>
          <AlertProvider>
            {children}
          </AlertProvider>
        </UserProvider>
      </body>
    </html>
  );
}
